name: gst_bill_app
description: GST Bill Generator
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.11.1
  printing: ^5.13.0
  path_provider: ^2.1.4
  share_plus: ^10.0.0
  shared_preferences: ^2.3.0
  intl: ^0.19.0

flutter:
  uses-material-design: true
